name: Deploy to staging
on:
  push:
    branches:
      - "main"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" > ~/.ssh/id_rsa_dev
          chmod 400 ~/.ssh/id_rsa_dev
          ssh-keyscan -H 52.90.189.25 >> ~/.ssh/known_hosts

      - name: Deploy to staging
        run: |
          ssh -i ~/.ssh/id_rsa_dev ubuntu@52.90.189.25 '
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd /home/ubuntu/bms &&
            git pull &&
            # Use full path if npm is not in PATH
            if command -v npm &> /dev/null; then
              npm install -g pnpm pm2
            else
              /usr/bin/npm install -g pnpm pm2 || /usr/local/bin/npm install -g pnpm pm2
            fi &&
            pnpm install &&
            pnpm run build &&
            pm2 restart all
          '
 