name: Deploy to staging
on:
  push:
    branches:
      - "main"
jobs:
  redeploy_everything:
    name: Deploying everything to staging cluster
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" > ~/.ssh_key_dev
          chmod 600 ~/.ssh_key_dev
          ssh -o StrictHostKeyChecking=no -i ~/.ssh_key_dev ubuntu@52.90.189.25
          cd bms && git pull
          npm install -g pnpm pm2
          pnpm install
          pnpm run build
          pm2 restart all